services:
  # Serviço do Banco de Dados MySQL
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prisma_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Serviço do Back-end (Node.js)
  app:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/prisma_db
      - TZ=America/Sao_Paulo
    ports:
      - "3000:3000"
    command: >
      sh -c "
        echo 'Aguardando o banco de dados iniciar...' &&
        wait-for-it db:3306 --timeout=30 &&
        echo 'Banco de dados pronto.' &&
        npx prisma generate &&
        echo 'Aplicando migrações...' &&
        npx prisma migrate deploy &&
        echo 'Populando o banco de dados com o seed...' &&
        npx prisma db seed &&
        echo 'Iniciando o servidor...' &&
        npm start
      "
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  # Serviço do Front-end (React)
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
